In [2]:
import numpy as np

In [4]:
l = [1,2,3,4]

In [6]:
np.array(l)

array([1, 2, 3, 4])

In [43]:
p = np.array([[1,2,3],[1,2,'a']])

In [44]:
p

array([['1', '2', '3'],
       ['1', '2', 'a']], dtype='<U11')

In [12]:
type(p)

numpy.ndarray

In [14]:
p[0]

array([1, 2, 3])

In [16]:
p[0][0]

1

In [23]:
o = np.array([1,2,3], ndmin = 10)

In [25]:
o

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [29]:
o = np.array([1,2,3] , dtype = float)

In [30]:
o

array([1., 2., 3.])

In [34]:
o = np.array([1,2,3] , dtype = complex)

In [35]:
o

array([1.+0.j, 2.+0.j, 3.+0.j])

In [37]:
u = np.array([(1,2),(3,4)])

In [42]:
u

array([[1, 2],
       [3, 4]])

In [47]:
t = np.mat([1,2,3])

In [49]:
t

matrix([[1, 2, 3]])

In [51]:
j = np.array(t)

In [53]:
type(j)

numpy.ndarray

In [55]:
l = [1,2,3,4]


In [58]:
h = np.asanyarray(l)

In [60]:
h

array([1, 2, 3, 4])

In [62]:
k = np.asanyarray(t)

In [64]:
k

matrix([[1, 2, 3]])

In [66]:
type(k)

numpy.matrix

In [68]:
a = [1,2,3,4]

In [70]:
b = a

In [72]:
b[0] = 434

In [74]:
b

[434, 2, 3, 4]

In [76]:
a

[434, 2, 3, 4]

In [78]:
c = np.copy(b)

In [80]:
c

array([434,   2,   3,   4])

In [82]:
b

[434, 2, 3, 4]

In [84]:
c[0] = 4344

In [86]:
c

array([4344,    2,    3,    4])

In [88]:
b

[434, 2, 3, 4]

In [90]:
l = np.array([[1,2,3],[4,5,6]])

In [93]:
l

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
l.shape

(2, 3)

In [97]:
l.size

6

In [99]:
l.dtype

dtype('int32')

In [ ]:
l.ndim